name: Facebook Bot

on:
  workflow_dispatch:
  schedule:
     - cron: "44 23 * * *"
     - cron: "44 06 * * *"  

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # ðŸ‘‰ TIDAK PERLU set DATE di workflow
      # ðŸ‘‰ TANGGAL DIAMBIL DARI index.js (WIB)

      - name: Run Puppeteer bot
        run: node docs/index.js
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

      - name: Upload recordings
        uses: actions/upload-artifact@v4
        with:
          name: recordings
          path: recording_*.mp4
          
